In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [106]:
credit=pd.read_csv("A:\Data Science/assignments/Logoistic Regression/creditcard.csv")

In [3]:
credit.shape

(1319, 13)

In [145]:
credit.head()

card  reports       age  income     share  expenditure selfemp  dependents  \
0  yes        0  37.66667  4.5200  0.033270   124.983300      no           3   
1  yes        0  33.25000  2.4200  0.005217     9.854167      no           3   
2  yes        0  33.66667  4.5000  0.004156    15.000000      no           4   
3  yes        0  30.50000  2.5400  0.065214   137.869200      no           0   
4  yes        0  32.16667  9.7867  0.067051   546.503300      no           2   

   months  majorcards  active  
0      54           1      12  
1      34           1      13  
2      58           1       5  
3      25           1       7  
4      64           1       5

In [113]:
credit=credit.iloc[:,1:]

In [107]:
card_dummy=pd.get_dummies(credit.card)

In [82]:
np.sum(card_dummy)

no      296
yes    1023
dtype: int64

In [112]:
card_dummy.head()

card
0     1
1     1
2     1
3     1
4     1

In [109]:
card_dummy=card_dummy.drop(['no'],axis=1)

In [124]:
card_dummy.head()

card
0     1
1     1
2     1
3     1
4     1

In [111]:
card_dummy=card_dummy.rename(columns={'yes':'card'})

In [47]:
credit.head()

reports       age  income     share  expenditure  dependents  months  \
0        0  37.66667  4.5200  0.033270   124.983300           3      54   
1        0  33.25000  2.4200  0.005217     9.854167           3      34   
2        0  33.66667  4.5000  0.004156    15.000000           4      58   
3        0  30.50000  2.5400  0.065214   137.869200           0      25   
4        0  32.16667  9.7867  0.067051   546.503300           2      64   

   majorcards  active  
0           1      12  
1           1      13  
2           1       5  
3           1       7  
4           1       5

In [116]:
owner_dummy=pd.get_dummies(credit.owner)

In [118]:
owner_dummy=owner_dummy.drop(['no'],axis=1)

In [122]:
owner_dummy=owner_dummy.rename(columns={'yes':'owner'})

In [123]:
owner_dummy.head()

owner
0      1
1      0
2      1
3      0
4      1

In [125]:
selfemp_dummy=pd.get_dummies(credit.selfemp)

In [127]:
selfemp_dummy=selfemp_dummy.drop(['no'],axis=1)

In [130]:
selfemp_dummy=selfemp_dummy.rename(columns={'yes':'selfemp'})

In [131]:
selfemp_dummy.head()

selfemp
0        0
1        0
2        0
3        0
4        0

In [143]:
credit.head()

card  reports       age  income     share  expenditure selfemp  dependents  \
0  yes        0  37.66667  4.5200  0.033270   124.983300      no           3   
1  yes        0  33.25000  2.4200  0.005217     9.854167      no           3   
2  yes        0  33.66667  4.5000  0.004156    15.000000      no           4   
3  yes        0  30.50000  2.5400  0.065214   137.869200      no           0   
4  yes        0  32.16667  9.7867  0.067051   546.503300      no           2   

   months  majorcards  active  
0      54           1      12  
1      34           1      13  
2      58           1       5  
3      25           1       7  
4      64           1       5

In [141]:
owner_dummy.head()

owner
0      1
1      0
2      1
3      0
4      1

In [146]:
del credit['card']

In [147]:
del credit['selfemp']

In [49]:
frames=[credit,card_dummy,owner_dummy,selfemp_dummy]

In [148]:
credit_card=pd.concat([credit,card_dummy,owner_dummy,selfemp_dummy],axis=1)

In [149]:
credit_card.head()

reports       age  income     share  expenditure  dependents  months  \
0        0  37.66667  4.5200  0.033270   124.983300           3      54   
1        0  33.25000  2.4200  0.005217     9.854167           3      34   
2        0  33.66667  4.5000  0.004156    15.000000           4      58   
3        0  30.50000  2.5400  0.065214   137.869200           0      25   
4        0  32.16667  9.7867  0.067051   546.503300           2      64   

   majorcards  active  card  owner  selfemp  
0           1      12     1      1        0  
1           1      13     1      0        0  
2           1       5     1      1        0  
3           1       7     1      0        0  
4           1       5     1      1        0

In [150]:
credit_card.dtypes

reports          int64
age            float64
income         float64
share          float64
expenditure    float64
dependents       int64
months           int64
majorcards       int64
active           int64
card             uint8
owner            uint8
selfemp          uint8
dtype: object

In [152]:
from sklearn.linear_model import LogisticRegression

In [158]:
x=credit_card.iloc[:,0:8]
y=credit_card.iloc[:,9]

In [160]:
x.head()

reports       age  income     share  expenditure  dependents  months  \
0        0  37.66667  4.5200  0.033270   124.983300           3      54   
1        0  33.25000  2.4200  0.005217     9.854167           3      34   
2        0  33.66667  4.5000  0.004156    15.000000           4      58   
3        0  30.50000  2.5400  0.065214   137.869200           0      25   
4        0  32.16667  9.7867  0.067051   546.503300           2      64   

   majorcards  
0           1  
1           1  
2           1  
3           1  
4           1

In [163]:
model=LogisticRegression()
credit_model=model.fit(x,y)

In [164]:
y_predicted=credit_model.predict(x)

In [167]:
from sklearn.metrics import confusion_matrix

In [169]:
con=confusion_matrix(y_predicted,y)

In [175]:
con

array([[ 296,   23],
       [   0, 1000]], dtype=int64)

In [181]:
con1=confusion_matrix(y,y_predicted)
print(con1)

[[ 296    0]
 [  23 1000]]


In [172]:
credit_card.card.value_counts()

1    1023
0     296
Name: card, dtype: int64

In [179]:
z=sum(y_predicted==0)
z

319

In [180]:
o=sum(y_predicted==1)
o

1000

In [191]:
Accuracy=sum(y_predicted==y)/credit_card.shape[0]
print('Accuracy of the model',Accuracy*100)


Accuracy of the model 98.25625473843822


In [186]:
Error=1-Accuracy
Error

0.01743745261561791

In [192]:
pd.crosstab(y_predicted,y)


card     0     1
row_0           
0      296    23
1        0  1000

In [193]:
#spliting Train and Test
from sklearn.model_selection import train_test_split

In [195]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=9)

In [196]:
model_1=LogisticRegression()
log_model=model_1.fit(x_train,y_train)

In [197]:
predicted_model=log_model.predict(x_test)

In [202]:
ER567890-confusion_matrix(predicted_model,y_test)

array([[ 70,   6],
       [  0, 188]], dtype=int64)

In [215]:
pd.crosstab(y_test,predicted_model)

col_0   0    1
card          
0      70    0
1       6  188

In [214]:
y_test.value_counts()

1    194
0     70
Name: card, dtype: int64

In [208]:
accuracy=sum(predicted_model==y_test)/x_test.shape[0]
accuracy

0.9772727272727273

In [209]:
Error=1-accuracy
Error

0.022727272727272707

In [216]:
Senstivity=188/(188+6)
Senstivity

0.9690721649484536

In [217]:
Precision=188/(188+0)
Precision

1.0